'use client'; // Runs on client (browser) side

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

// Type definition for data (props) passed to product form component
interface ProductFormProps {
  // Event handler executed on form submission
  onSubmit: (e: React.FormEvent<HTMLFormElement>) => void;
  // Initial values to set for input fields
  initialValues?: {
    name: string;
    image_url?: string | null | undefined;
    description?: string | null | undefined;
    price: number;
    stock?: number;
    is_featured?: boolean;
  };
  submitLabel: string; // Display text for form submit button
}

// Common style for input fields
const inputStyle = 'w-full border border-gray-300 px-3 py-2 rounded-sm focus:ring-2 focus:ring-brand-500';
// Common style for labels
const labelStyle = "block font-bold mb-1";
// Common style for badges (indicating required fields)
const badgeStyle = "ml-2 px-2 py-0.5 bg-red-500 text-white text-xs font-semibold rounded-md";

// Common product form component
export default function ProductForm({
  onSubmit,
  initialValues = { name: '', image_url: '', description: '', price: 0, stock: 0, is_featured: false },
  submitLabel,
}: ProductFormProps) {
  const router = useRouter();
  const [previewUrl, setPreviewUrl] = useState('');

  // Display registered image initially if available
  useEffect(() => {
    if (initialValues.image_url) {
      setPreviewUrl(`/uploads/${initialValues.image_url}`);
    }
  }, [initialValues.image_url]);

  // Release temporary URL generated by URL.createObjectURL()
  useEffect(() => {
    return () => {
      if (previewUrl && previewUrl.startsWith('blob:')) {
        URL.revokeObjectURL(previewUrl);
      }
    };
  }, [previewUrl]);

  // Event handler for image file selection
  const handleImageChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) { // Clear preview
      setPreviewUrl('');
      return;
    }

    // Generate temporary URL for displaying image in browser
    const tempUrl = URL.createObjectURL(file);
    setPreviewUrl(tempUrl);
  };

  // Event handler for cancel action
  const handleCancel = () => {
    // Show confirmation dialog
    if (confirm('Input content will be discarded. Are you sure?')) {
      router.push('/admin/products'); // Navigate to admin product list page
    }
  };

  return (
    <form
      onSubmit={onSubmit} encType="multipart/form-data"
      className="w-full space-y-6 p-8 bg-white shadow-lg rounded-xl"
    >
      <label className={labelStyle} htmlFor="name">
        Product Name<span className={badgeStyle}>Required</span>
      </label>
      <input type="text" id="name" name="name" required
        defaultValue={initialValues.name} className={inputStyle}
      />

      <label className={labelStyle} htmlFor="imageFile">
        Product Image<span className={badgeStyle}>Required</span>
      </label>
      <div className="flex flex-col gap-6 mt-2">
        <input type="file" id="imageFile" name="imageFile"
          required={!initialValues.image_url}
          accept="image/*" // Allow image files only
          onChange={handleImageChange}
          className="text-gray-600 file:bg-gray-50 file:border file:border-gray-300 file:px-4 file:py-2 file:rounded-sm file:cursor-pointer"
        />
        {previewUrl && (
          <div className="px-8" id="imagePreview">
            {/* Since the preview image uses a temporary blob URL, <Image> should not be used here */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={previewUrl} alt="preview" className="object-cover rounded-md shadow-md" />
          </div>
        )}
      </div>

      <label className={labelStyle} htmlFor="description">
        Description
      </label>
      <textarea id="description" name="description" rows={5}
        defaultValue={initialValues.description ?? ''} className={inputStyle}
      />

      <label className={labelStyle} htmlFor="price">
        Price (tax included)<span className={badgeStyle}>Required</span>
      </label>
      <input type="number" id="price" name="price" required
        min="0" step="1" // Allow integers 0 and above only
        defaultValue={initialValues.price} className={inputStyle}
      />

      <label className={labelStyle} htmlFor="stock">
        Stock Quantity<span className={badgeStyle}>Required</span>
      </label>
      <input type="number" id="stock" name="stock" required
        min="0" step="1" // Allow integers 0 and above only
        defaultValue={initialValues.stock} className={inputStyle}
      />

     <label className={labelStyle} htmlFor="isFeatured" >
        <input
          type="checkbox" id="isFeatured" name="isFeatured"
          defaultChecked={initialValues.is_featured} className="mr-2"
        />
        Display as featured product
      </label>

      <div className="flex justify-end space-x-4 mt-6">
        <button type="button" onClick={handleCancel}
          className="w-1/2 bg-gray-200 hover:bg-gray-300 text-gray-700 py-2 rounded-sm"
        >
          Cancel
        </button>
        <button type="submit"
          className="w-1/2 bg-brand-500 hover:bg-brand-600 text-white font-semibold py-2 rounded-sm"
        >
          {submitLabel}
        </button>
      </div>
    </form>
  );
}